sudo: required
services:
  - docker

before_install:
  - docker build -t spacex -f Dockerfile.dev .

script:
  - docker run -e CI=true spacex npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "spacex"
  env: "Spacex-env"
  bucket_name: "elasticbeanstalk-us-east-2-892524062431"
  bucket_path: "spacex"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY